CREATE DATABASE partTimeJob DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

CREATE USER 'wowman'@'%' IDENTIFIED BY '1q2w3e!';
CREATE USER 'wowman'@'localhost' IDENTIFIED BY '1q2w3e!';

USE mysql;

-- DB 별 권한 부여
GRANT ALL PRIVILEGES ON *.* TO 'wowman'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'wowman'@'localhost' WITH GRANT OPTION;

-- 마무리.
FLUSH PRIVILEGES;